# Generated by Django 4.1.7 on 2023-03-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_user_type_alter_user_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_phone',
            field=models.SmallIntegerField(default=0),
        ),
    ]
