# Generated by Django 4.1.7 on 2023-03-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.SmallIntegerField(default=0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farmer_fname',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farmer_lname',
        ),
        migrations.AddField(
            model_name='farmer',
            name='farmer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='products',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=5)),
                ('product_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.customer')),
            ],
        ),
    ]
