# Generated by Django 4.1.7 on 2023-03-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_customer_remove_farmer_farmer_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
