# Generated by Django 4.1.7 on 2023-03-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_product_product_image_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
