# Generated by Django 4.1.7 on 2023-03-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_product_product_by_delete_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodcut_quantity',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
