# Generated by Django 4.1.7 on 2023-03-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_product_prodcut_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodcut_quantity',
            new_name='product_quantity',
        ),
    ]
